spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: ${AUTH_DB_USER:postgres}
    password: ${AUTH_DB_PASS:12345}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update