server:
  port: 8083

spring:
  application:
    name: report-service
  boot:
    admin:
      client:
        url: http://localhost:8084  # Admin server URL
  actuator:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,prometheus
    endpoint:
      health:
        show-details: always

jwt:
  secret: ${JWT_SECRET}

report:
  cache-ttl-seconds: 300