spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      ssl:
        enabled: true
  tracking:
    base-url: ${TRACKING_SERVICE_URL:http://tracking-service:8082}
