server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: ${GATEWAY_AUTH_URI}
          predicates:
            - Path=/auth/**

        - id: tracking
          uri: ${GATEWAY_TRACKING_URI}
          predicates:
            - Path=/tracking/**

        - id: reports
          uri: ${GATEWAY_REPORTS_URI}
          predicates:
            - Path=/reports/**