/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#7aeb9d",
        "surface-bright": "#2c2c2c",
        "inverse-on-surface": "#555555",
        "on-secondary-fixed-variant": "#006a36",
        "on-error": "#450900",
        "on-secondary": "#005f30",
        "surface-container-high": "#1f1f1f",
        "on-background": "#ffffff",
        "surface-tint": "#9cff93",
        "on-primary-fixed": "#00440a",
        "on-tertiary-fixed": "#003d42",
        "surface-container-lowest": "#000000",
        "surface-container": "#191919",
        "primary-fixed": "#00fc40",
        "surface-variant": "#262626",
        "on-surface": "#ffffff",
        "on-tertiary-container": "#005159",
        "secondary": "#89faaa",
        "primary-container": "#00fc40",
        "outline": "#757575",
        "outline-variant": "#484848",
        "tertiary-fixed": "#0eeafd",
        "on-primary-fixed-variant": "#006513",
        "secondary-container": "#006d38",
        "on-surface-variant": "#ababab",
        "on-secondary-container": "#e3ffe5",
        "tertiary-dim": "#00dbec",
        "surface-container-highest": "#262626",
        "tertiary": "#8af2ff",
        "primary-fixed-dim": "#00ec3b",
        "on-error-container": "#ffd2c8",
        "on-secondary-fixed": "#004a24",
        "tertiary-fixed-dim": "#00dbec",
        "background": "#0e0e0e",
        "secondary-fixed": "#89faaa",
        "on-primary-container": "#005a10",
        "secondary-dim": "#7aeb9d",
        "surface": "#0e0e0e",
        "surface-container-low": "#131313",
        "error": "#ff7351",
        "surface-dim": "#0e0e0e",
        "primary": "#9cff93",
        "inverse-surface": "#f9f9f9",
        "error-dim": "#d53d18",
        "on-primary": "#006413",
        "error-container": "#b92902",
        "inverse-primary": "#006f16",
        "on-tertiary": "#005b63",
        "on-tertiary-fixed-variant": "#005c64",
        "primary-dim": "#00ec3b",
        "tertiary-container": "#0eeafd"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "mono": ["Space Grotesk", "monospace"]
      },
      borderRadius: {
        "DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "2xl": "1rem", "3xl": "1.5rem", "full": "9999px"
      },
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
